feat: Add base events aggregator
trudan-studios/sky-mavis pull request #4
Opened 2024-09-27 17:03 UTC by TheJarX

[WIP]
TODO:

- [ ] Use events API key (the one they send in the request body
- [ ] Use an **actual** background job (?)
- [ ] Discuss if we really need redis
- [ ] Add Docker file and deploy to staging

2024-09-27 17:05 UTC, TheJarX commented
This seem to be working. This version basically receives the events acting as proxy and stores them before sending them in digestible batches to the Mavis API. Pretty much the same as a CloudFlare worker

2024-09-27 21:31 UTC, julionav requested changes

2024-09-27 21:31 UTC, julionav commented on mavis-aggregator/src/index.ts
> +    while (true) {
I'm more or less sure the size limit is per request -- so this needs to happen AFTER grouping the events. 

Similar to the rate limit, it likely exist per API key

2024-09-27 21:31 UTC, julionav commented on mavis-aggregator/src/index.ts
> +    while (true) {
The fact that we are using TS doesn't mean we need to throw away what our lord .NET taught us. 

Keep this simple. Make a class for handling the event sending per api key

2024-09-27 21:31 UTC, julionav commented
We definetely don't need redis for this @TheJarX, so lets not add it. 
Few reasons why we don't:
- These are analytical events, so while they are important, it won't be the end of the world if some are lost for some reason

2024-09-30 15:00 UTC, julionav approved these changes
This is looking much better, nice job! Ship it

2024-09-30 16:11 UTC, merged